# Generated by Django 5.1.6 on 2025-02-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projeto/imagens/')),
                ('link', models.URLField(blank=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
